### PR TITLE
Fix bug where arguments with spaces don't work

### PR DESCRIPTION
**Pull request by jaypinho**
As mentioned in issue #35 and discussed at greater length here (https://bugs.chromium.org/p/chromedriver/issues/detail?id=2276#c7), this buildpack incorrectly handles user agents and other args with spaces in them.

### CODE REVIEW

**Comment by stereoscott** [comment]
Thank you for this! Took us a while to land here after realizing our custom user agents were failing in CI.

**Comment by jskirst** [comment]
Looks like this has been held up for almost a year. Any chance this can be merged? having to use @jaypinho's forked version isn't ideal.

**Comment by lucasmarinb** [comment]
> Looks like this has been held up for more than a year. Any chance this can be merged? having to use @jaypinho's forked version isn't ideal.

+1

**Comment by chrismaltais** [comment]
👋 Any update on this?

**Comment by TuHechiceroFavorito** [comment]
Any updates? I'm using my own forked version to apply the suggested change because the pull request doesn't have the new recent updates. Which is a problem for future updates. If this change could be included it would be really helpful

**Comment by jaypinho** [comment]
Tried to resolve conflicts so we can get this into the main branch!

**Review by joeybrown-sf — APPROVED** [review]
thank you for the PR, @jaypinho !

**Comment by joeybrown-sf** [comment]
@heroku/production-services This release did not follow our compliance process because this is not one of our officially supported buildpacks & changeling was holding up the merge.

**Pull request merged**
